config/routes.rb
Rails.application.routes.draw do
  namespace :admins_backoffice do
    get 'admins/index'
    get 'welcome/index'
    resources :admins # criar as rotas p/ admins
    resources :types
    resources :grape_types
    resources :countries
    resources :wines
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end

  namespace :site do
    get 'welcome/index'
  end

  devise_for :users
  devise_for :admins

  root to: 'site/welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destory]

  def index
    @admins = Admin.all.page(params[:page])
  end

  def edit
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_index_path, notice: "Create Successfull!"
    else
      render :new
    end
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Update Successfull!"
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: "Destroy Successful!"
    else
      render :index
    end
  end
  
  
  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
  
  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
  

end

app/controllers/admins_backoffice/countries_controller.rb
class AdminsBackoffice::CountriesController < AdminsBackofficeController
  before_action :set_country, only: [:edit, :update, :destory]

  def index
    @countries = Country.all.page(params[:page])
  end

  def edit
  end

  def new
    @country = Country.new
  end

  def create
    @country = Country.new(params_country)
    if @country.save
      redirect_to admins_backoffice_countries_path, notice: "Create Successfull!"
    else
      render :new
    end
  end

  def update
    if @country.update(params_country)
      redirect_to admins_backoffice_countries_path, notice: "Update Successfull!"
    else
      render :edit
    end
  end

  def destroy
    if @country.destroy
      redirect_to admins_backoffice_countries_path, notice: "Destroy Successful!"
    else
      render :index
    end
  end
  
  private

  def set_country
    @country = Country.find(params[:id])
  end

  def params_country
    params.require(:country).permit(:description)
  end

end

app/controllers/admins_backoffice/grape_types_controller.rb
class AdminsBackoffice::GrapeTypesController < AdminsBackofficeController
  before_action :set_grape_type, only: [:edit, :update, :destory]

  def index
    @grape_types = GrapeType.all.page(params[:page])
  end

  def edit
  end

  def new
    @grape_type = GrapeType.new
  end

  def create
    @grape_type = GrapeType.new(params_grape_type)
    if @grape_type.save
      redirect_to admins_backoffice_grape_types_path, notice: "Create Successfull!"
    else
      render :new
    end
  end

  def update
    if @grape_type.update(params_grape_type)
      redirect_to admins_backoffice_grape_types_path, notice: "Update Successfull!"
    else
      render :edit
    end
  end

  def destroy
    if @grape_type.destroy
      redirect_to admins_backoffice_grape_types_path, notice: "Destroy Successful!"
    else
      render :index
    end
  end
  
  private

  def set_grape_type
    @grape_type = GrapeType.find(params[:id])
  end

  def params_grape_type
    params.require(:grape_type).permit(:description)
  end
end

app/controllers/admins_backoffice/types_controller.rb
class AdminsBackoffice::TypesController < AdminsBackofficeController
  before_action :set_type, only: [:edit, :update, :destory]

  def index
    @types = Type.all.page(params[:page])
  end

  def edit
  end

  def new
    @type = Type.new
  end

  def create
    @type = Type.new(params_type)
    if @type.save
      redirect_to admins_backoffice_types_path, notice: "Create Successfull!"
    else
      render :new
    end
  end

  def update
    if @type.update(params_type)
      redirect_to admins_backoffice_types_path, notice: "Update Successfull!"
    else
      render :edit
    end
  end

  def destroy
    if @type.destroy
      redirect_to admins_backoffice_types_path, notice: "Destroy Successful!"
    else
      render :index
    end
  end
  
  private

  def set_type
    @type = Type.find(params[:id])
  end

  def params_type
    params.require(:type).permit(:description)
  end
  
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice/wines_controller.rb
class AdminsBackoffice::WinesController < AdminsBackofficeController
  before_action :set_wine, only: [:edit, :update, :destory]

  def index
    @wines = Wine.all.page(params[:page]).per(5)
  end

  def edit
  end

  def new
    @wine = Wine.new
  end

  def create
    @wine = Wine.new(params_wine)
    @wine.admin = current_admin
    
    if @wine.save
      redirect_to admins_backoffice_wines_path, notice: "Create Successfull!"
    else
      render :new
    end
  end

  def update
    if @wine.update(params_wine)
      redirect_to admins_backoffice_wines_path, notice: "Update Successfull!"
    else
      render :edit
    end
  end

  def destroy
    if @wine.destroy
      redirect_to admins_backoffice_wines_path, notice: "Destroy Successful!"
    else
      render :index
    end
  end
  
  private

  def set_wine
    @wine = Wine.find(params[:id])
  end

  def params_wine
    params.require(:wine).permit(:description, :type_id, :grape_type_id, :country_id, :price, :amount, :url_img)
  end

end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/countries_helper.rb
module AdminsBackoffice::CountriesHelper
end

app/helpers/admins_backoffice/grape_types_helper.rb
module AdminsBackoffice::GrapeTypesHelper
end

app/helpers/admins_backoffice/types_helper.rb
module AdminsBackoffice::TypesHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice/wines_helper.rb
module AdminsBackoffice::WinesHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/views/admins_backoffice/grape_types/edit.html.erb
<%= render partial: 'admins_backoffice/grape_types/shared/form',
  locals: {action_message: 'Edit Grape Type'}  
%>

app/views/admins_backoffice/grape_types/index.html.erb
<div class='container'>
  <div class='row justify-content-right'>
    <div class="col-6">
      <h4 class='page-header'>Grape Types</h4>
    </div>
  </div>
</div>

<div class='container'>
  <div class='row justify-content-right'>
    <div class="col-6">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Id</th>
            <th scope="col">Description</th>
            <th>
              <%= link_to new_admins_backoffice_grape_type_path	, class:'btn btn-outline-success btn-sm' do %>
                New
              <% end %>
            </th>
          </tr>
        </thead>
        <tbody>
          <% @grape_types.each do |gtype|%>
          <tr>
            <td><%= gtype.id %></td>
            <td><%= gtype.description %></td>
            <td>
              <%= link_to edit_admins_backoffice_grape_type_path(gtype), class:'btn btn-outline-primary btn-sm' do %>
                  Edit
                <% end %>
                <%= link_to admins_backoffice_grape_type_path(gtype), method: :delete, class:'btn btn-outline-danger btn-sm', data: {confirm: 'Are You Sure?'} do %>
                  Delete
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class='container'>
        <div class='row justify-content-center'>
          <div class="col-6 pagination-sm">
            <%= paginate @grape_types %>
          </div>
        </div>
      </div>  

    </div>
  </div>
</div>

app/views/admins_backoffice/grape_types/new.html.erb
<%= render partial: 'admins_backoffice/grape_types/shared/form',
  locals: {action_message: 'New Grape Type'}  
%>